PRAGMA foreign_keys = ON;

CREATE TABLE cfp_forms (
 id TEXT NOT NULL PRIMARY KEY, organization_id TEXT NOT NULL, event_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','published','closed')), welcome_content TEXT NOT NULL, speaker_limit INTEGER NOT NULL CHECK(speaker_limit>0), max_submissions_per_account INTEGER NOT NULL CHECK(max_submissions_per_account>0), reminders_enabled INTEGER NOT NULL CHECK(reminders_enabled IN(0,1)), admin_notifications_enabled INTEGER NOT NULL CHECK(admin_notifications_enabled IN(0,1)), confirmation_message TEXT NOT NULL, success_content TEXT NOT NULL, redirect_url TEXT, version INTEGER NOT NULL CHECK(version>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE CASCADE, UNIQUE(organization_id,id), UNIQUE(organization_id,event_id,id)
) STRICT;
CREATE INDEX cfp_forms_event_status_name_idx ON cfp_forms(organization_id,event_id,status,name);
CREATE TABLE cfp_form_sections (organization_id TEXT NOT NULL, form_id TEXT NOT NULL, id TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, sort_order INTEGER NOT NULL CHECK(sort_order>=0), PRIMARY KEY(organization_id,form_id,id), FOREIGN KEY(organization_id,form_id) REFERENCES cfp_forms(organization_id,id) ON DELETE CASCADE, UNIQUE(organization_id,form_id,sort_order)) STRICT;
CREATE INDEX cfp_form_sections_order_idx ON cfp_form_sections(organization_id,form_id,sort_order);
CREATE TABLE reusable_fields (organization_id TEXT NOT NULL REFERENCES organizations(organization_id) ON DELETE CASCADE, id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), definition_json TEXT NOT NULL CHECK(json_valid(definition_json) AND json_type(definition_json)='object'), created_at TEXT NOT NULL, PRIMARY KEY(organization_id,id,version)) STRICT;
CREATE INDEX reusable_fields_versions_idx ON reusable_fields(organization_id,id,version DESC);
CREATE TABLE cfp_form_fields (
 organization_id TEXT NOT NULL, form_id TEXT NOT NULL, id TEXT NOT NULL, section_id TEXT NOT NULL, scope TEXT NOT NULL CHECK(scope IN('submission','participant')), field_key TEXT NOT NULL, label TEXT NOT NULL, description TEXT, placeholder TEXT, kind TEXT NOT NULL CHECK(kind IN('file_request','text','rich_text','email','select','multi_select','boolean','number')), required INTEGER NOT NULL CHECK(required IN(0,1)), options_json TEXT NOT NULL CHECK(json_valid(options_json) AND json_type(options_json)='array'), file_owner TEXT, allowed_mime_types_json TEXT CHECK(allowed_mime_types_json IS NULL OR (json_valid(allowed_mime_types_json) AND json_type(allowed_mime_types_json)='array')), max_bytes INTEGER, reusable_field_id TEXT, reusable_field_version INTEGER, sort_order INTEGER NOT NULL CHECK(sort_order>=0),
 PRIMARY KEY(organization_id,form_id,id), FOREIGN KEY(organization_id,form_id) REFERENCES cfp_forms(organization_id,id) ON DELETE CASCADE, FOREIGN KEY(organization_id,form_id,section_id) REFERENCES cfp_form_sections(organization_id,form_id,id) ON DELETE CASCADE, FOREIGN KEY(organization_id,reusable_field_id,reusable_field_version) REFERENCES reusable_fields(organization_id,id,version) ON DELETE RESTRICT,
 UNIQUE(organization_id,form_id,field_key), UNIQUE(organization_id,form_id,scope,sort_order),
 CHECK((kind='file_request' AND file_owner IN('submission','participant') AND allowed_mime_types_json IS NOT NULL AND max_bytes>0) OR (kind<>'file_request' AND file_owner IS NULL AND allowed_mime_types_json IS NULL AND max_bytes IS NULL)), CHECK((reusable_field_id IS NULL)=(reusable_field_version IS NULL))
) STRICT;
CREATE INDEX cfp_form_fields_order_idx ON cfp_form_fields(organization_id,form_id,scope,sort_order);
CREATE INDEX cfp_form_fields_reusable_idx ON cfp_form_fields(organization_id,reusable_field_id,reusable_field_version);
CREATE TABLE cfp_form_rules (organization_id TEXT NOT NULL, form_id TEXT NOT NULL, id TEXT NOT NULL, priority INTEGER NOT NULL CHECK(priority>=0), condition_json TEXT NOT NULL CHECK(json_valid(condition_json) AND json_type(condition_json)='object'), actions_json TEXT NOT NULL CHECK(json_valid(actions_json) AND json_type(actions_json)='array'), PRIMARY KEY(organization_id,form_id,id), FOREIGN KEY(organization_id,form_id) REFERENCES cfp_forms(organization_id,id) ON DELETE CASCADE, UNIQUE(organization_id,form_id,priority)) STRICT;
CREATE INDEX cfp_form_rules_priority_idx ON cfp_form_rules(organization_id,form_id,priority);

CREATE TABLE submissions (
 id TEXT NOT NULL PRIMARY KEY, organization_id TEXT NOT NULL, event_id TEXT NOT NULL, form_id TEXT NOT NULL, owner_account_id TEXT NOT NULL, form_version INTEGER NOT NULL CHECK(form_version>0), status TEXT NOT NULL CHECK(status IN('draft','submitted','reopened','withdrawn')), completed_steps_json TEXT NOT NULL CHECK(json_valid(completed_steps_json) AND json_type(completed_steps_json)='array'), version INTEGER NOT NULL CHECK(version>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, submitted_at TEXT, reopened_at TEXT, withdrawn_at TEXT, final_decision_at TEXT,
 FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE RESTRICT, FOREIGN KEY(organization_id,event_id,form_id) REFERENCES cfp_forms(organization_id,event_id,id) ON DELETE RESTRICT, UNIQUE(organization_id,id), UNIQUE(organization_id,event_id,id)
) STRICT;
CREATE INDEX submissions_event_updated_idx ON submissions(organization_id,event_id,updated_at DESC);
CREATE INDEX submissions_owner_form_idx ON submissions(organization_id,event_id,form_id,owner_account_id);
CREATE INDEX submissions_status_idx ON submissions(organization_id,event_id,status,updated_at DESC);

CREATE TABLE participants (
 id TEXT NOT NULL PRIMARY KEY, organization_id TEXT NOT NULL, event_id TEXT NOT NULL, first_name TEXT NOT NULL, last_name TEXT NOT NULL, display_name TEXT NOT NULL, email TEXT NOT NULL, normalized_email TEXT NOT NULL COLLATE NOCASE, identity_state TEXT NOT NULL CHECK(identity_state IN('resolved','ambiguous')), source_type TEXT NOT NULL CHECK(source_type IN('cfp','manual','csv','crm')), source_id TEXT, claimed_user_id TEXT REFERENCES auth_users(id) ON DELETE SET NULL, version INTEGER NOT NULL CHECK(version>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL,
 FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE CASCADE, UNIQUE(organization_id,id), UNIQUE(organization_id,event_id,id)
) STRICT;
CREATE UNIQUE INDEX participants_resolved_email_uidx ON participants(organization_id,event_id,normalized_email) WHERE normalized_email<>'' AND identity_state='resolved';
CREATE INDEX participants_email_idx ON participants(organization_id,event_id,normalized_email);
CREATE INDEX participants_source_idx ON participants(organization_id,event_id,source_type,source_id);

CREATE TABLE submission_participants (organization_id TEXT NOT NULL,event_id TEXT NOT NULL,submission_id TEXT NOT NULL,participant_id TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('primary','co_speaker')),biography TEXT NOT NULL,answers_json TEXT NOT NULL CHECK(json_valid(answers_json) AND json_type(answers_json)='object'),ordinal INTEGER NOT NULL CHECK(ordinal>=0),PRIMARY KEY(organization_id,submission_id,participant_id),FOREIGN KEY(organization_id,event_id,submission_id) REFERENCES submissions(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT,UNIQUE(organization_id,submission_id,ordinal)) STRICT;
CREATE UNIQUE INDEX submission_participants_primary_uidx ON submission_participants(organization_id,submission_id) WHERE role='primary';
CREATE INDEX submission_participants_participant_idx ON submission_participants(organization_id,event_id,participant_id,submission_id);
CREATE TABLE submission_secondary_contacts (organization_id TEXT NOT NULL,submission_id TEXT NOT NULL,id TEXT NOT NULL,name TEXT NOT NULL,email TEXT NOT NULL,ordinal INTEGER NOT NULL CHECK(ordinal>=0),PRIMARY KEY(organization_id,submission_id,id),FOREIGN KEY(organization_id,submission_id) REFERENCES submissions(organization_id,id) ON DELETE CASCADE,UNIQUE(organization_id,submission_id,ordinal)) STRICT;
CREATE INDEX submission_secondary_contacts_order_idx ON submission_secondary_contacts(organization_id,submission_id,ordinal);
CREATE TABLE submission_versions (organization_id TEXT NOT NULL,event_id TEXT NOT NULL,submission_id TEXT NOT NULL,version INTEGER NOT NULL CHECK(version>0),reason TEXT NOT NULL CHECK(reason IN('draft_created','draft_saved','submitted','reopened','withdrawn')),actor_id TEXT NOT NULL,idempotency_key TEXT,snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json) AND json_type(snapshot_json)='object'),created_at TEXT NOT NULL,PRIMARY KEY(organization_id,submission_id,version),FOREIGN KEY(organization_id,event_id,submission_id) REFERENCES submissions(organization_id,event_id,id) ON DELETE RESTRICT) STRICT;
CREATE UNIQUE INDEX submission_versions_idempotency_uidx ON submission_versions(organization_id,submission_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX submission_versions_event_time_idx ON submission_versions(organization_id,event_id,created_at DESC);

CREATE TABLE speaker_tasks (
 id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,submission_id TEXT,participant_id TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN('form','upload','action')),owner TEXT NOT NULL CHECK(owner IN('speaker','organizer')),title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',instructions TEXT NOT NULL DEFAULT '',status TEXT NOT NULL CHECK(status IN('not_started','in_progress','submitted','needs_changes','completed','waived','overdue','reopened')),due_at TEXT,allowed_mime_types_json TEXT NOT NULL CHECK(json_valid(allowed_mime_types_json) AND json_type(allowed_mime_types_json)='array'),max_bytes INTEGER CHECK(max_bytes IS NULL OR max_bytes>0),accepted_asset_kinds_json TEXT NOT NULL CHECK(json_valid(accepted_asset_kinds_json) AND json_type(accepted_asset_kinds_json)='array'),version INTEGER NOT NULL CHECK(version>0),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,
 FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,submission_id) REFERENCES submissions(organization_id,event_id,id) ON DELETE RESTRICT,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id)
) STRICT;
CREATE INDEX speaker_tasks_participant_status_idx ON speaker_tasks(organization_id,event_id,participant_id,status,due_at);
CREATE INDEX speaker_tasks_submission_idx ON speaker_tasks(organization_id,event_id,submission_id);
CREATE TABLE speaker_task_dependencies (organization_id TEXT NOT NULL,event_id TEXT NOT NULL,task_id TEXT NOT NULL,dependency_task_id TEXT NOT NULL,PRIMARY KEY(organization_id,event_id,task_id,dependency_task_id),FOREIGN KEY(organization_id,event_id,task_id) REFERENCES speaker_tasks(organization_id,event_id,id) ON DELETE CASCADE,FOREIGN KEY(organization_id,event_id,dependency_task_id) REFERENCES speaker_tasks(organization_id,event_id,id) ON DELETE CASCADE,CHECK(task_id<>dependency_task_id)) STRICT;
CREATE INDEX speaker_task_dependencies_reverse_idx ON speaker_task_dependencies(organization_id,event_id,dependency_task_id);
CREATE TABLE speaker_task_reminder_offsets (organization_id TEXT NOT NULL,event_id TEXT NOT NULL,task_id TEXT NOT NULL,offset_minutes INTEGER NOT NULL CHECK(offset_minutes>=0),PRIMARY KEY(organization_id,event_id,task_id,offset_minutes),FOREIGN KEY(organization_id,event_id,task_id) REFERENCES speaker_tasks(organization_id,event_id,id) ON DELETE CASCADE) STRICT;
CREATE TABLE speaker_task_transitions (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,task_id TEXT NOT NULL,participant_id TEXT NOT NULL,actor_account_id TEXT NOT NULL,from_status TEXT NOT NULL CHECK(from_status IN('not_started','in_progress','submitted','needs_changes','completed','waived','overdue','reopened')),to_status TEXT NOT NULL CHECK(to_status IN('not_started','in_progress','submitted','needs_changes','completed','waived','overdue','reopened')),note TEXT,occurred_at TEXT NOT NULL,FOREIGN KEY(organization_id,event_id,task_id) REFERENCES speaker_tasks(organization_id,event_id,id) ON DELETE RESTRICT) STRICT;
CREATE INDEX speaker_task_transitions_time_idx ON speaker_task_transitions(organization_id,event_id,task_id,occurred_at);

CREATE TABLE speaker_assets (
 id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,submission_id TEXT,participant_id TEXT NOT NULL,task_id TEXT,kind TEXT NOT NULL CHECK(kind IN('headshot','slides','supporting_file')),object_key TEXT NOT NULL UNIQUE,file_name TEXT NOT NULL,content_type TEXT NOT NULL,size_bytes INTEGER NOT NULL CHECK(size_bytes>=0),state TEXT NOT NULL CHECK(state IN('pending_upload','ready','rejected')),version INTEGER NOT NULL CHECK(version>0),version_family_id TEXT NOT NULL,supersedes_asset_id TEXT,comment_thread_id TEXT NOT NULL,review_state TEXT CHECK(review_state IN('approved','needs_changes')),review_note TEXT,reviewed_at TEXT,reviewed_by TEXT,review_version INTEGER NOT NULL DEFAULT 0 CHECK(review_version>=0),latest_version_id TEXT,current_version_id TEXT,approved_version_id TEXT,released_version_id TEXT,rejection_reason TEXT,created_at TEXT NOT NULL,finalized_at TEXT,
 FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,submission_id) REFERENCES submissions(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,task_id) REFERENCES speaker_tasks(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(supersedes_asset_id) REFERENCES speaker_assets(id) ON DELETE RESTRICT,
 UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id),UNIQUE(organization_id,event_id,version_family_id,version),CHECK((review_state IS NULL AND reviewed_at IS NULL AND reviewed_by IS NULL) OR (review_state IS NOT NULL AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)),CHECK(state<>'rejected' OR rejection_reason IS NOT NULL)
) STRICT;
CREATE INDEX speaker_assets_participant_idx ON speaker_assets(organization_id,event_id,participant_id,created_at DESC);
CREATE INDEX speaker_assets_task_idx ON speaker_assets(organization_id,event_id,task_id,created_at DESC);
CREATE INDEX speaker_assets_family_idx ON speaker_assets(organization_id,event_id,version_family_id,version DESC);
CREATE INDEX speaker_assets_state_idx ON speaker_assets(organization_id,event_id,state,created_at DESC);
CREATE INDEX speaker_assets_released_idx ON speaker_assets(released_version_id);

CREATE TABLE submission_answers (organization_id TEXT NOT NULL,submission_id TEXT NOT NULL,field_key TEXT NOT NULL,value_json TEXT NOT NULL CHECK(json_valid(value_json)),asset_id TEXT,PRIMARY KEY(organization_id,submission_id,field_key),FOREIGN KEY(organization_id,submission_id) REFERENCES submissions(organization_id,id) ON DELETE CASCADE,FOREIGN KEY(asset_id) REFERENCES speaker_assets(id) ON DELETE RESTRICT) STRICT;
CREATE INDEX submission_answers_submission_idx ON submission_answers(organization_id,submission_id);
CREATE INDEX submission_answers_asset_idx ON submission_answers(asset_id);

CREATE TABLE speaker_profiles (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,participant_id TEXT NOT NULL,display_name TEXT NOT NULL,email TEXT,job_title TEXT NOT NULL DEFAULT '',company TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT '',biography TEXT NOT NULL,social_links_json TEXT NOT NULL CHECK(json_valid(social_links_json) AND json_type(social_links_json)='object'),travel_required INTEGER NOT NULL CHECK(travel_required IN(0,1)),arrival_at TEXT,departure_at TEXT,accommodation TEXT NOT NULL DEFAULT '',dietary_requirements TEXT NOT NULL DEFAULT '',accessibility_needs TEXT NOT NULL DEFAULT '',travel_notes TEXT NOT NULL DEFAULT '',headshot_asset_id TEXT,source_type TEXT CHECK(source_type IN('cfp','manual','csv','crm')),source_id TEXT,version INTEGER NOT NULL CHECK(version>0),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(organization_id,event_id,participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(headshot_asset_id) REFERENCES speaker_assets(id) ON DELETE SET NULL,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id),UNIQUE(organization_id,event_id,participant_id)) STRICT;
CREATE INDEX speaker_profiles_participant_idx ON speaker_profiles(organization_id,event_id,participant_id);
CREATE INDEX speaker_profiles_status_idx ON speaker_profiles(organization_id,event_id,status);
CREATE INDEX speaker_profiles_source_idx ON speaker_profiles(organization_id,event_id,source_type,source_id);

CREATE TABLE speaker_roster (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,submission_id TEXT NOT NULL,participant_id TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('primary','co_speaker')),status TEXT NOT NULL CHECK(status IN('pending','active','revoked')),workflow_status TEXT,organizer_status TEXT,display_name TEXT NOT NULL,email TEXT,job_title TEXT NOT NULL,company TEXT NOT NULL,biography TEXT NOT NULL,social_links_json TEXT NOT NULL CHECK(json_valid(social_links_json) AND json_type(social_links_json)='object'),travel_logistics_json TEXT NOT NULL CHECK(json_valid(travel_logistics_json) AND json_type(travel_logistics_json)='object'),headshot_asset_id TEXT,source_type TEXT CHECK(source_type IN('cfp','manual','csv','crm')),source_id TEXT,version INTEGER NOT NULL CHECK(version>0),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,author_account_id TEXT,FOREIGN KEY(organization_id,event_id,submission_id) REFERENCES submissions(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(headshot_asset_id) REFERENCES speaker_assets(id) ON DELETE SET NULL,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id),UNIQUE(organization_id,event_id,submission_id,participant_id)) STRICT;
CREATE INDEX speaker_roster_submission_idx ON speaker_roster(organization_id,event_id,submission_id,status);
CREATE INDEX speaker_roster_participant_idx ON speaker_roster(organization_id,event_id,participant_id,status);
CREATE INDEX speaker_roster_status_idx ON speaker_roster(organization_id,event_id,status,updated_at DESC);

CREATE TABLE speaker_task_forms (id TEXT NOT NULL,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,task_id TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL,fields_json TEXT NOT NULL CHECK(json_valid(fields_json) AND json_type(fields_json)='array'),version INTEGER NOT NULL CHECK(version>0),published INTEGER NOT NULL CHECK(published IN(0,1)),updated_at TEXT NOT NULL,PRIMARY KEY(id,version),FOREIGN KEY(organization_id,event_id,task_id) REFERENCES speaker_tasks(organization_id,event_id,id) ON DELETE RESTRICT,UNIQUE(organization_id,event_id,task_id,version)) STRICT;
CREATE UNIQUE INDEX speaker_task_forms_published_uidx ON speaker_task_forms(organization_id,event_id,task_id) WHERE published=1;
CREATE INDEX speaker_task_forms_versions_idx ON speaker_task_forms(organization_id,event_id,task_id,version DESC);
CREATE TABLE speaker_task_responses (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,task_id TEXT NOT NULL,participant_id TEXT NOT NULL,definition_version INTEGER NOT NULL CHECK(definition_version>0),answers_json TEXT NOT NULL CHECK(json_valid(answers_json) AND json_type(answers_json)='object'),status TEXT NOT NULL CHECK(status IN('draft','submitted','needs_changes','reopened')),version INTEGER NOT NULL CHECK(version>0),feedback TEXT,submitted_at TEXT,updated_at TEXT NOT NULL,FOREIGN KEY(organization_id,event_id,task_id) REFERENCES speaker_tasks(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(organization_id,event_id,participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT,FOREIGN KEY(task_id,definition_version) REFERENCES speaker_task_forms(id,version) ON DELETE RESTRICT,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,task_id,participant_id,version)) STRICT;
CREATE INDEX speaker_task_responses_latest_idx ON speaker_task_responses(organization_id,event_id,task_id,participant_id,version DESC);
CREATE TABLE speaker_asset_comments (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,asset_id TEXT NOT NULL,version_id TEXT NOT NULL,body TEXT NOT NULL,author_label TEXT NOT NULL,author_account_id TEXT,version INTEGER NOT NULL CHECK(version>0),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(asset_id) REFERENCES speaker_assets(id) ON DELETE RESTRICT) STRICT;
CREATE INDEX speaker_asset_comments_version_idx ON speaker_asset_comments(organization_id,event_id,asset_id,version_id,created_at);

CREATE TABLE portal_contexts (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,account_id TEXT NOT NULL,name TEXT NOT NULL,slug TEXT NOT NULL COLLATE NOCASE,status TEXT NOT NULL,primary_participant_id TEXT NOT NULL,capabilities_json TEXT NOT NULL CHECK(json_valid(capabilities_json) AND json_type(capabilities_json)='array'),version INTEGER NOT NULL CHECK(version>0),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE CASCADE,FOREIGN KEY(organization_id,event_id,primary_participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id),UNIQUE(organization_id,event_id,account_id,id),UNIQUE(organization_id,event_id,slug)) STRICT;
CREATE INDEX portal_contexts_account_idx ON portal_contexts(organization_id,event_id,account_id);
CREATE INDEX portal_contexts_event_idx ON portal_contexts(organization_id,event_id,status);
CREATE TABLE portal_context_submissions (organization_id TEXT NOT NULL,event_id TEXT NOT NULL,context_id TEXT NOT NULL,submission_id TEXT NOT NULL,PRIMARY KEY(organization_id,event_id,context_id,submission_id),FOREIGN KEY(organization_id,event_id,context_id) REFERENCES portal_contexts(organization_id,event_id,id) ON DELETE CASCADE,FOREIGN KEY(organization_id,event_id,submission_id) REFERENCES submissions(organization_id,event_id,id) ON DELETE RESTRICT) STRICT;
CREATE INDEX portal_context_submissions_submission_idx ON portal_context_submissions(organization_id,event_id,submission_id);
CREATE TABLE portal_context_participants (organization_id TEXT NOT NULL,event_id TEXT NOT NULL,context_id TEXT NOT NULL,participant_id TEXT NOT NULL,PRIMARY KEY(organization_id,event_id,context_id,participant_id),FOREIGN KEY(organization_id,event_id,context_id) REFERENCES portal_contexts(organization_id,event_id,id) ON DELETE CASCADE,FOREIGN KEY(organization_id,event_id,participant_id) REFERENCES participants(organization_id,event_id,id) ON DELETE RESTRICT) STRICT;
CREATE INDEX portal_context_participants_participant_idx ON portal_context_participants(organization_id,event_id,participant_id);

CREATE TABLE speaker_event_resources (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,title TEXT NOT NULL,summary TEXT,html TEXT,url TEXT,sort_order INTEGER NOT NULL CHECK(sort_order>=0),status TEXT NOT NULL CHECK(status IN('draft','published','archived')),version INTEGER NOT NULL CHECK(version>0),updated_at TEXT NOT NULL,FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE CASCADE,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id),UNIQUE(organization_id,event_id,sort_order)) STRICT;
CREATE INDEX speaker_event_resources_order_idx ON speaker_event_resources(organization_id,event_id,sort_order);
CREATE TABLE speaker_wiki_pages (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,title TEXT NOT NULL,slug TEXT NOT NULL COLLATE NOCASE,summary TEXT,html TEXT,url TEXT,sort_order INTEGER NOT NULL CHECK(sort_order>=0),status TEXT NOT NULL CHECK(status IN('draft','published','archived')),version INTEGER NOT NULL CHECK(version>0),updated_at TEXT NOT NULL,FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE CASCADE,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id),UNIQUE(organization_id,event_id,sort_order),UNIQUE(organization_id,event_id,slug)) STRICT;
CREATE INDEX speaker_wiki_pages_order_idx ON speaker_wiki_pages(organization_id,event_id,sort_order);
CREATE TABLE speaker_content (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,entity_type TEXT NOT NULL CHECK(entity_type IN('session','speaker')),entity_id TEXT NOT NULL,title TEXT,description TEXT,abstract TEXT,biography TEXT,social_links_json TEXT CHECK(social_links_json IS NULL OR (json_valid(social_links_json) AND json_type(social_links_json)='object')),headshot_asset_id TEXT,status TEXT,version INTEGER NOT NULL CHECK(version>0),updated_at TEXT NOT NULL,updated_by TEXT NOT NULL,FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE CASCADE,FOREIGN KEY(headshot_asset_id) REFERENCES speaker_assets(id) ON DELETE SET NULL,UNIQUE(organization_id,id),UNIQUE(organization_id,event_id,id),UNIQUE(organization_id,event_id,entity_type,entity_id)) STRICT;
CREATE INDEX speaker_content_source_idx ON speaker_content(organization_id,event_id,entity_type,entity_id);
CREATE TABLE speaker_content_history (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,entity_type TEXT NOT NULL CHECK(entity_type IN('session','speaker')),entity_id TEXT NOT NULL,action TEXT NOT NULL CHECK(action IN('created','updated','restored','approved','needs_changes')),version INTEGER NOT NULL CHECK(version>0),actor_account_id TEXT NOT NULL,actor_label TEXT,occurred_at TEXT NOT NULL,snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json) AND json_type(snapshot_json)='object'),FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE RESTRICT,UNIQUE(organization_id,event_id,entity_type,entity_id,version)) STRICT;
CREATE INDEX speaker_content_history_source_idx ON speaker_content_history(organization_id,event_id,entity_type,entity_id,version DESC);
CREATE TABLE speaker_reminder_receipts (id TEXT NOT NULL PRIMARY KEY,organization_id TEXT NOT NULL,event_id TEXT NOT NULL,idempotency_key TEXT NOT NULL,task_ids_json TEXT NOT NULL CHECK(json_valid(task_ids_json) AND json_type(task_ids_json)='array'),recipient_ids_json TEXT NOT NULL CHECK(json_valid(recipient_ids_json) AND json_type(recipient_ids_json)='array'),receipts_json TEXT NOT NULL CHECK(json_valid(receipts_json) AND json_type(receipts_json)='array'),actor_account_id TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(organization_id,event_id) REFERENCES events(organization_id,id) ON DELETE RESTRICT,UNIQUE(organization_id,event_id,idempotency_key)) STRICT;
CREATE INDEX speaker_reminder_receipts_time_idx ON speaker_reminder_receipts(organization_id,event_id,created_at DESC);
