import type { CfpConfiguration } from "./cfp-editor-model";

export function createTestCfpConfiguration(eventId = "summit-2026"): CfpConfiguration {
  return {
    eventName: "Eventloom Summit 2026",
    slug: eventId,
    timezone: "America/Los_Angeles",
    opensAt: "2026-01-15",
    closesAt: "2026-03-31",
    participantLimit: 3,
    proposalLimit: 3,
    reminderEmails: true,
    adminNotifications: true,
    welcomeTitle: "Bring your best session to the Summit",
    welcomeBody: "Tell us what attendees will learn.",
    confirmationTitle: "Your proposal is in",
    confirmationBody: "Thanks for sharing your idea.",
    successMessage: "Your proposal was submitted.",
    redirectUrl: "",
    tracks: ["Product craft", "Community systems", "Responsible AI"],
    tags: ["Accessibility", "Leadership"],
    formats: ["Talk · 30 minutes", "Workshop · 60 minutes"],
    levels: ["Introductory", "Intermediate", "Advanced"],
    helpfulLinks: [{ label: "Speaker guide", href: "https://example.test/speaker-guide" }],
    fields: [
      {
        id: "proposal-title",
        key: "title",
        label: "Proposal title",
        type: "text",
        kind: "text",
        required: true,
        visible: true,
        placeholder: "A clear title",
        options: [],
      },
      {
        id: "abstract",
        key: "abstract",
        label: "Proposal abstract",
        type: "textarea",
        kind: "rich_text",
        required: true,
        visible: true,
        placeholder: "What will attendees learn?",
        options: [],
      },
      {
        id: "accessibility-notes",
        key: "accessibility-notes",
        label: "Accessibility notes",
        type: "textarea",
        kind: "rich_text",
        required: false,
        visible: true,
        placeholder: "Share access needs",
        options: [],
      },
      {
        id: "website",
        key: "website",
        label: "Website",
        type: "url",
        kind: "url",
        required: false,
        visible: true,
        placeholder: "https://",
        options: [],
      },
    ],
    rule: {
      type: "condition",
      field: "format",
      operator: "is",
      value: "Workshop · 60 minutes",
    },
    ruleAction: "show Accessibility notes",
    ruleTargetField: "accessibility-notes",
  };
}
