export {
  type AirtableBaseMapping,
  type AirtableConflict,
  type AirtableConflictResolution,
  type AirtableConflictResolutionInput,
  type AirtableConnectionState,
  AirtableIntegration,
  type AirtableIntegrationApi,
  AirtableIntegrationApiError,
  type AirtableIntegrationProps,
  type AirtableIntegrationSnapshot,
  type AirtableProjectionFailure,
  type AirtableProjectionHealth,
  type AirtableProjectionStatus,
  type AirtableSyncDirection,
  type AirtableTableMapping,
  createAirtableIntegrationApi,
} from "./airtable-integration";
